### ISSUE TITLE
any issue with a BN plugin?

### ISSUE THREAD

**Issue by psifertex** [rizinorg/rz-silhouette#7]
I noticed the server has pre-shared key access. I'm curious if that's just to prevent potential abuse or if there is a desire to only limit it to rizin/cutter clients? In other words, is there any issue if I were to write a compatible Binary Ninja plugin? Related: if I were to write a compatible plugin, would you be interested/willing to have it be merged into this repo as a shared codebase or would you prefer I keep the code separate? 

Related: I haven't looked at the source yet, just the documentation describing the architecture as I don't see a license on this repo. Obviously I can only view the source during my plugin creation and use that knowledge if it will be released under an open source license. Can you clarify what license this repo is available under?

**Comment by XVilka** [comment]
Personally, I am fine with having the plugin in the same repository. The PSK is used to prevent abuses. In the future, we should think about how to ensure the quality and relevance of the shared content and avoid spam in a more meaningful way. Any ideas for this are welcome.

**Comment by wargio** [comment]
> I noticed the server has pre-shared key access. I'm curious if that's just to prevent potential abuse or if there is a desire to only limit it to rizin/cutter clients? In other words, is there any issue if I were to write a compatible Binary Ninja plugin? Related: if I were to write a compatible plugin, would you be interested/willing to have it be merged into this repo as a shared codebase or would you prefer I keep the code separate?
> 
> Related: I haven't looked at the source yet, just the documentation describing the architecture as I don't see a license on this repo. Obviously I can only view the source during my plugin creation and use that knowledge if it will be released under an open source license. Can you clarify what license this repo is available under?

No, you can definitively use that. it's FOSS and yes, you can implement a client for BN or Ghidra or IDA.

**Comment by psifertex** [comment]
Thanks to both of you for the feedback. No promises on the timeline, but it's a great idea. We've even been internally playing around with the idea of a similar system with open source plugins for all RE tools. Would be happy to collaborate but for now I figure just implementing a plugin for this would be a good place to start and see if any ideas come from it.

Thanks @wargio -- I was just afraid to look into the source specifically just in case they weren't intended to be OSS and I didn't want to be tainted (I mean, knowing the team behind it I figured that was _probably_ the intention but I just wanted to be careful).

Thanks.
